image: cmiles74/docker-ubuntu

stages:
  - build
  - deploy
 
build:
  stage: build
  script:
    - lein deps
    - lein uberjar
    - lein launch4j
  artifacts:
    paths:
      - target/*-standalone.jar
      - target/*.exe
