name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-linux:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 13
          java-package: jdk+fx
      - name: Build project
        run: bin/lein with-profile linux64 build-dist
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: linux64-xmltool
          path: dist/linux64
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.upload_artifact.outputs.upload_url }}
          asset_path: ./linux64-xmltool
          asset_name: linux64-xmltool.zip
          asset_content_type: application/zip
  build-macos:
    runs-on: [macos-latest]
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 13
          java-package: jdk+fx
      - name: Build project
        run: bin/lein with-profile mac build-dist
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: macos-xmltool
          path: dist/mac
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.upload_artifact.outputs.upload_url }}
          asset_path: ./macos-xmltool
          asset_name: macos-xmltool.zip
          asset_content_type: application/zip
  build-windows:
    runs-on: [windows-latest]
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 13
          java-package: jdk+fx
      - name: Build project
        run: bin/lein self-install; bin/lein with-profile windows64 build-dist
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: windows64-xmltool
          path: dist/windows64
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.upload_artifact.outputs.upload_url }}
          asset_path: ./windows64-xmltool
          asset_name: windows64-xmltool.zip
          asset_content_type: application/zip

