name: Release

on:
  push:
    branches:
      - 'main'

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.release_draft.outputs.upload_url }}
    steps:
      - id: release_draft
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-linux:
    needs: update_release_draft
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 13
          java-package: jdk+fx
      - name: Setup Leiningen
        uses: DeLaGuardo/setup-clojure@master
        with:
          lein: latest
      - name: Build project
        run: lein with-profile linux64 build-dist
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: linux64-xmltool
          path: dist/linux64
      - name: Create Artifact Archive
        uses: montudor/action-zip@v0.1.0
          with:
            args: zip -qq -r xmltool-linux64.zip dist/linux64
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.update_release_draft.outputs.upload_url }}
          asset_path: xmltool-linux64.zip
          asset_name: xmltool-linux64.zip
          asset_content_type: application/zip
  build-macos:
    needs: update_release_draft
    runs-on: [macos-latest]
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 13
          java-package: jdk+fx
      - name: Setup Leiningen
        uses: DeLaGuardo/setup-clojure@master
        with:
          lein: latest
      - name: Build project
        run: lein with-profile mac build-dist
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: macos-xmltool
          path: dist/mac
      - name: Create Artifact Archive
        uses: montudor/action-zip@v0.1.0
          with:
            args: zip -qq -r xmltool-macos.zip dist/mac
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.update_release_draft.outputs.upload_url }}
          asset_path: xmltool-macos.zip
          asset_name: xmltool-macos.zip
          asset_content_type: application/zip
  build-windows:
    needs: update_release_draft
    runs-on: [windows-latest]
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 13
          java-package: jdk+fx
      - name: Setup Leiningen
        uses: DeLaGuardo/setup-clojure@master
        with:
          lein: latest
      - name: Build project
        run: lein with-profile windows64 build-dist
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: windows64-xmltool
          path: dist/windows64
      - name: Create Artifact Archive
        uses: montudor/action-zip@v0.1.0
          with:
            args: zip -qq -r xmltool-windows64.zip dist/windows64
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.update_release_draft.outputs.upload_url }}
          asset_path: xmltool-windows64.zip
          asset_name: xmltool-windows64.zip
          asset_content_type: application/zip


